### ISSUE TITLE
Déployer sur heroku

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/lpa2-back-P2020#1]
Deployer le site sous heroku:

- enlever sqllite3 du groupe production
- ajouter la gem pg dans le groupe de production.

Attention pour mettre a jour le gemfile.lock il faut lancer `bundle install --without production`
Attention au rails db:migrate

vous me postez ici: 
Votre nom prenom
le lien vers github action de votre projet
le lien vers herko/burgers qui marche !!!

**Comment by thoKling** [comment]
KLING Thomas
https://github.com/thoKling/Burgers/actions
https://lpa2burgers.herokuapp.com/burgers/

**Comment by SamuelPelsy** [comment]
PELSY-MOZIMANN Samuel
https://github.com/SamuelPelsy/LPA2/actions
https://lpa2-spelsy.herokuapp.com/burgers

**Comment by Manouuu** [comment]
LACROIX Emmanuel
https://github.com/Manouuu/LPA2/actions
https://lpa22.herokuapp.com/burgers

**Comment by leabrnr** [comment]
BRUNORI Léa
https://github.com/leabrnr/lpa2/actions
https://lpa2-lbrunori.herokuapp.com/burgers

**Comment by lripoche** [comment]
RIPOCHE Lucas
https://github.com/lripoche/LP71-homework/actions
https://lpa2-ripoche.herokuapp.com/burgers

**Comment by Caybe** [comment]
CABEZAS Mathias
https://github.com/Caybe/LPA2/actions
https://lpa2-utbm.herokuapp.com/burgers

**Comment by mael-brdn** [comment]
BOURDON Maël
https://github.com/mael-brdn/lpa2/actions
https://lpa2-mael.herokuapp.com/burgers

**Comment by AlexandreDHE** [comment]
DELAHOUSSE Alexandre
https://github.com/AlexandreDHE/UTBM_LPA2-Back-P2020/actions
https://utbm-lpa2-p2020-delahousse.herokuapp.com/burgers

**Comment by AntoineMURE** [comment]
MURÉ Antoine
https://github.com/AntoineMURE/LPA2/actions
https://lpa2amur.herokuapp.com/burgers

**Comment by flamerant** [comment]
LAMÉRANT Félicie
https://github.com/flamerant/lpa2-back-P2020/actions
https://lpa2felicie.herokuapp.com/burgers

**Comment by Fantome071** [comment]
DEBUIGNY Léo
https://github.com/Fantome071/rails_01
https://fantome071-rails-01.herokuapp.com/burgers

**Comment by AlixCoat** [comment]
COATLEVEN Alix
https://github.com/AlixCoat/UTBM_LPA2-Back-P2020/actions
https://rails-tp.herokuapp.com/burgers

**Comment by AdrienFoucaultUTBM** [comment]
FOUCAULT Adrien
https://github.com/AdrienFoucaultUTBM/lpa2-back-p20
https://lpa2afoucault.herokuapp.com/burgers

**Comment by HugoL90** [comment]
LAURENT Hugo
https://github.com/HugoL90/BurgerApp
https://burgerapp90.herokuapp.com/burgers

**Comment by Gyskard** [comment]
MARGUERITAT Thomas
https://github.com/Gyskard/rails-burger/actions
https://gyskard-rails.herokuapp.com/burgers/

**Comment by DamienM39** [comment]
MUSY Damien
https://github.com/DamienM39/LPA2/actions
https://lpa2-dmsy.herokuapp.com/burgers/

**Comment by KillianMrg** [comment]
MORGE Killian
https://github.com/KillianMrg/Burgers/actions
https://appburgers.herokuapp.com/burgers

**Comment by zaturgo** [comment]
BLANCHARD Hugo
https://github.com/zaturgo/LPA2-Rails-Continuous-Deployment/actions
https://lpa2-rails.herokuapp.com/burgers

**Comment by alexis-dtrvl** [comment]
DAUTREVILLE Alexis
https://github.com/alexis-dtrvl/lpa2_project_2020/actions
https://lpa2-dautreville.herokuapp.com/burgers

**Comment by Stygma7** [comment]
HIRTH Matthieu
https://github.com/Stygma7/rails-burger/actions
https://styg-rails.herokuapp.com/burgers

**Comment by Duresapz** [comment]
PAJAZITI Duresa
https://github.com/Duresapz/lp2---s2/actions
https://lp2---s2.herokuapp.com/burgers

**Comment by youbensahra** [comment]
Youssef Ben Sahra
https://github.com/youbensahra/Project-Burgers/actions
https://blooming-fortress-98829.herokuapp.com/burgers

**Comment by Quent1nl** [comment]
LAM Quentin
https://github.com/Quent1nl/LP/actions
https://lpburgers.herokuapp.com/burgers

**Comment by MatraneBadr** [comment]
Matrane Badr
https://github.com/MatraneBadr/LP71-Homework/actions
https://lp71-burgers.herokuapp.com/burgers

**Comment by mamieve15** [comment]
Awa BA
https://github.com/mamieve15/lpa2-back-P2020/actions
http://lpa2-back.herokuapp.com/burgers

**Comment by HassanBzd** [comment]
Hassan Bouzid
https://burgerlpa2.herokuapp.com/burgers/
https://github.com/HassanBzd/LPA2-Project/actions

**Comment by nicolas-fremondiere** [comment]
Fremondiere Nicolas
https://github.com/nicolas-fremondiere/lpa2/actions
https://lpa2-nicolas.herokuapp.com/burgers

**Comment by ChloeViei** [comment]
Vieille Chloé
https://github.com/ChloeViei/test_application_rails/actions
https://test-application-rails.herokuapp.com/burgers

**Comment by glechant** [comment]
Lechantre Guillaume
https://github.com/glechant/LPA2/actions
https://lpa2-glechant.herokuapp.com/burgers

**Comment by LPA2-Automne2016** [comment]
Bravo tout le monde 👍
