### ISSUE TITLE
charger les nutriments depuis l'API

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/lpa2-back-P2020#2]
- modifier le model pour ajouter la methode nutriments qui appelle le WS openfoodfacts
- modifier toutes les vues pour intégrer le code du burger
- modier la vue show : / burger/1 pour y ajouter un tableau des nutriments
- modifier le JSON pour inclure les nutriments

publier ici:
nom prénom
lien vers la page des burgers sous heroku
lien vers github

**Comment by SamuelPelsy** [comment]
PELSY-MOZIMANN Samuel
https://github.com/SamuelPelsy/LPA2/actions
https://lpa2-spelsy.herokuapp.com/burgers

**Comment by leabrnr** [comment]
BRUNORI Léa
https://lpa2-lbrunori.herokuapp.com/burgers
https://github.com/leabrnr/lpa2

**Comment by lripoche** [comment]
RIPOCHE Lucas
https://lpa2-ripoche.herokuapp.com/burgers
https://github.com/lripoche/LP71-homework/actions

**Comment by Manouuu** [comment]
LACROIX Emmanuel
https://lpa22.herokuapp.com/burgers
https://github.com/Manouuu/LPA2/actions

**Comment by Fantome071** [comment]
DEBUIGNY Léo
https://fantome071-rails-01.herokuapp.com/burgers
https://github.com/Fantome071/rails_01

**Comment by Gyskard** [comment]
MARGUERITAT Thomas
https://gyskard-rails.herokuapp.com/burgers
https://github.com/Gyskard/rails-burger/actions

**Comment by MatraneBadr** [comment]
Matrane Badr
https://lp71-burgers.herokuapp.com/burgers
https://github.com/MatraneBadr/LP71-Homework/actions

**Comment by AlexandreDHE** [comment]
DELAHOUSSE Alexandre
https://utbm-lpa2-p2020-delahousse.herokuapp.com/burgers
https://github.com/AlexandreDHE/UTBM_LPA2-Back-P2020/actions

**Comment by AntoineMURE** [comment]
MURÉ Antoine
https://lpa2amur.herokuapp.com/burgers
https://github.com/AntoineMURE/LPA2/actions

**Comment by nicolas-fremondiere** [comment]
FREMONDIERE Nicolas
https://lpa2-nicolas.herokuapp.com/burgers
https://github.com/nicolas-fremondiere/lpa2/actions

**Comment by m-cabezas** [comment]
CABEZAS Mathias
https://lpa2-utbm.herokuapp.com/burgers
https://github.com/Caybe/LPA2/actions

**Comment by HugoL90** [comment]
LAURENT Hugo
https://burgerapp90.herokuapp.com/burgers
https://github.com/HugoL90/BurgerApp/actions

**Comment by zaturgo** [comment]
BLANCHARD Hugo
https://lpa2-rails.herokuapp.com/burgers
https://github.com/zaturgo/LPA2-Rails-Continuous-Deployment/actions

**Comment by youbensahra** [comment]
BEN SAHRA Youssef
https://blooming-fortress-98829.herokuapp.com/burgers
https://github.com/youbensahra/Project-Burgers/actions

**Comment by thoKling** [comment]
KLING Thomas
https://lpa2burgers.herokuapp.com/burgers
https://github.com/thoKling/Burgers/actions

**Comment by dmusy** [comment]
MUSY Damien
https://lpa2-dmsy.herokuapp.com/burgers
https://github.com/dmusy/LPA2/actions

**Comment by glechant** [comment]
Lechantre Guillaume
https://github.com/glechant/LPA2/actions
https://lpa2-glechant.herokuapp.com/burgers

**Comment by AlixCoat** [comment]
COATLEVEN Alix
https://rails-tp.herokuapp.com/burgers
https://github.com/AlixCoat/UTBM_LPA2-Back-P2020/actions

**Comment by KillianMrg** [comment]
MORGE Killian
https://github.com/KillianMrg/Burgers/actions
https://appburgers.herokuapp.com/burgers/1

**Comment by ChloeViei** [comment]
VIEILLE Chloé
https://test-application-rails.herokuapp.com/burgers
https://github.com/ChloeViei/test_application_rails/actions

**Comment by Styyg** [comment]
HIRTH Matthieu
https://styg-rails.herokuapp.com/burgers
https://github.com/Stygma7/rails-burger/actions

**Comment by mael-brdn** [comment]
Bourdon Maël
https://lpa2-mael.herokuapp.com/burgers
https://github.com/mael-brdn/lpa2/actions

**Comment by Quent1nl** [comment]
LAM Quentin
https://lpburgers.herokuapp.com/burgers
https://github.com/Quent1nl/LP/actions

**Comment by alexis-dtrvl** [comment]
DAUTREVILLE Alexis
https://lpa2-dautreville.herokuapp.com/burgers
https://github.com/alexis-dtrvl/lpa2_project_2020/actions

**Comment by Duresapz** [comment]
PAJAZITI Duresa
https://lp2---s2.herokuapp.com/burgers
https://github.com/Duresapz/lp2---s2/actions

**Comment by HassanBzd** [comment]
https://burgerlpa2.herokuapp.com/burgers
https://github.com/HassanBzd/LPA2-Project

**Comment by mamieve15** [comment]
BA Awa
https://rails-burgers.herokuapp.com/burgers
https://github.com/mamieve15/rails_burgers

**Comment by LPA2-Automne2016** [comment]
Bravo tout le monde, c'est une sans faute 👍
